services:
  redoc:
    container_name: doc-api-redoc
    image: redocly/redoc:v2.5.0
    environment:
      - PAGE_TITLE=Tooldata API
      - PAGE_FAVICON=https://app.tooldata.io/favicon.ico
      - SPEC_URL=https://raw.githubusercontent.com/tooldata/doc-api/master/openapi.yaml
    restart: unless-stopped

  nginx:
    container_name: doc-api-nginx
    image: nginx:alpine
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./openapi.yaml:/var/www/openapi.yaml:ro
    ports:
      - "8085:80"
    depends_on:
      - redoc
    restart: unless-stopped

networks:
  default:
    name: v2_default
    external: true
