version: '3'
services:
  redoc:
    container_name: redoc
    image: redocly/redoc:latest
    environment:
      - PAGE_TITLE=Tooldata API
      - PAGE_FAVICON=https://www.tooldata.io/favicon.ico
      - SPEC_URL=http://localhost/openapi.yaml
      - PORT=3000

  nginx:
    container_name: nginx_static
    image: nginx:latest
    volumes:
     - ./default.conf:/etc/nginx/conf.d/default.conf
     - .:/var/www
    ports:
      - 80:80
    links:
      - redoc
